In [2]:
!pip show tensorflow

Name: tensorflow
Version: 1.15.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.6/dist-packages
Requires: tensorflow-estimator, tensorboard, grpcio, numpy, wrapt, google-pasta, astor, opt-einsum, gast, termcolor, absl-py, wheel, keras-preprocessing, keras-applications, protobuf, six
Required-by: stable-baselines, magenta, fancyimpute


In [3]:
# For the current version: 
!pip install --upgrade tensorflow

     |████████████████████████████████| 86.3MB 76kB/s 
     |████████████████████████████████| 3.8MB 45.9MB/s 
     |████████████████████████████████| 450kB 26.6MB/s 
     |████████████████████████████████| 81kB 10.5MB/s 
ERROR: tensorboard 2.0.2 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.10.0 which is incompatible.
  Found existing installation: google-auth 1.4.2
    Uninstalling google-auth-1.4.2:
      Successfully uninstalled google-auth-1.4.2
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstall

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import h5py
import pandas as pd
import numpy as np

In [0]:
h5f = h5py.File("/content/drive/My Drive/Documents/Project-case_study-2/SVHN_single_grey1.h5",'r')

In [4]:
print("Keys: %s" % h5f.keys())
group_keys = list(h5f.keys())

# Get the data
for i in range(len(group_keys)):
  print(group_keys[i], len(list(h5f[group_keys[i]])))

Keys: KeysView(<HDF5 file "SVHN_single_grey1.h5" (mode r)>)
X_test 18000
X_train 42000
X_val 60000
y_test 18000
y_train 42000
y_val 60000


In [5]:
# Load the training, test and validation set
X_train = h5f['X_train'][:]
y_train = h5f['y_train'][:]
X_test = h5f['X_test'][:]
y_test = h5f['y_test'][:]
X_val = h5f['X_val'][:]
y_val = h5f['y_val'][:]

# Close this file
h5f.close()

print('Training set', X_train.shape, y_train.shape)
print('Validation set', X_val.shape, y_val.shape)
print('Test set', X_test.shape, y_test.shape)


Training set (42000, 32, 32) (42000,)
Validation set (60000, 32, 32) (60000,)
Test set (18000, 32, 32) (18000,)


In [0]:

X_test1 = np.asarray(X_test).reshape(18000, 32*32)
X_train1 = np.asarray(X_train).reshape(42000, 32*32)
X_val1 = np.asarray(X_val).reshape(60000, 32*32)
y_test1 = np.asarray(y_test).reshape(18000, 1)
y_train1 = np.asarray(y_train).reshape(42000, 1)
y_val1 = np.asarray(y_val).reshape(60000, 1)

KNN Classical Model Building

In [7]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train1, y_train1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [41]:
y_pred = knn.predict(X_val1)
print(accuracy_score(y_val1, y_pred))

0.6283166666666666


In [8]:
y_pred = knn.predict(X_val1)
print(accuracy_score(y_val1, y_pred))

0.6283166666666666


In [10]:
y_pred_test = knn.predict(X_test1)
print(accuracy_score(y_test1, y_pred_test))

0.4617777777777778


In [11]:
from sklearn import metrics

print(metrics.confusion_matrix(y_test1, y_pred_test))

[[1234   73   58   66   63   43  106   22   68   81]
 [ 135 1306  104   81   81   34   23   42   12   10]
 [ 154  285  967  112   55   29   25   97   33   46]
 [ 183  302  206  648   67  134   39   33   61   46]
 [ 200  303   65   76 1016   31   50   13   36   22]
 [ 248  192  116  326   76  561   99   16   80   54]
 [ 432  156   80  100  136  156  575    5  169   23]
 [ 162  283  162   89   34   25   21  987   13   32]
 [ 386  162  109  209   95  144  184   11  449   63]
 [ 460  168  124  137   72   84   75   37   78  569]]


In [12]:
from sklearn.metrics import classification_report
target_names = ['class 0', 'class 1', 'class 2', 'class 3', 'class 4', 'class 5', 'class 6', 'class 7', 'class 8', 'class 9']
print(classification_report(y_test1, y_pred_test, target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.34      0.68      0.46      1814
     class 1       0.40      0.71      0.52      1828
     class 2       0.49      0.54      0.51      1803
     class 3       0.35      0.38      0.36      1719
     class 4       0.60      0.56      0.58      1812
     class 5       0.45      0.32      0.37      1768
     class 6       0.48      0.31      0.38      1832
     class 7       0.78      0.55      0.64      1808
     class 8       0.45      0.25      0.32      1812
     class 9       0.60      0.32      0.41      1804

    accuracy                           0.46     18000
   macro avg       0.49      0.46      0.46     18000
weighted avg       0.50      0.46      0.46     18000



Implement a Neural Network

In [0]:
import tensorflow as tf

import tensorflow.keras
from tensorflow.keras import optimizers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout, Flatten, Reshape, BatchNormalization
from tensorflow.keras.layers import Convolution2D, MaxPooling2D

In [0]:
#ONE HOT VECTOR CONVERSION
y_train_c = tensorflow.keras.utils.to_categorical(y_train, num_classes=10)
y_test_c = tensorflow.keras.utils.to_categorical(y_test, num_classes=10)
y_val_c = tensorflow.keras.utils.to_categorical(y_val, num_classes=10)

In [22]:
print(X_train.shape, X_val.shape, X_test.shape)

(42000, 32, 32) (60000, 32, 32) (18000, 32, 32)


In [23]:
X_train_c = np.asarray(X_train).reshape(X_train.shape[0],X_train.shape[1], X_train.shape[2],1)
X_test_c = np.asarray(X_test).reshape(X_test.shape[0],X_test.shape[1], X_test.shape[2],1)
X_val_c = np.asarray(X_val).reshape(X_val.shape[0],X_val.shape[1], X_val.shape[2],1)

print(type(X_train_c), X_train_c.shape)
print(type(X_test_c), X_test_c.shape)
print(type(X_val_c), X_val_c.shape)

<class 'numpy.ndarray'> (42000, 32, 32, 1)
<class 'numpy.ndarray'> (18000, 32, 32, 1)
<class 'numpy.ndarray'> (60000, 32, 32, 1)


In [0]:
model = Sequential()
model.add(Reshape((1024,),input_shape=(32,32,1,)))
model.add(BatchNormalization())

model.add(Dense(200, activation='relu', name='Layer_1'))
model.add(Dense(100, activation='relu', name='Layer_2'))

model.add(Dense(60, activation='relu', name='Layer_3'))
model.add(Dense(30, activation='relu', name='Layer_4'))

model.add(Dense(10, activation='softmax', name='Output'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [25]:
model.fit(X_train_c,y_train_c,          
          validation_data=(X_val_c,y_val_c),
          epochs=30,
          batch_size=32)

Train on 42000 samples, validate on 60000 samples
Epoch 1/30
42000/42000 [==============================] - 14s 327us/sample - loss: 1.4404 - accuracy: 0.5146 - val_loss: 0.9651 - val_accuracy: 0.7002
Epoch 2/30
42000/42000 [==============================] - 12s 284us/sample - loss: 1.0057 - accuracy: 0.6793 - val_loss: 0.7930 - val_accuracy: 0.7529
Epoch 3/30
42000/42000 [==============================] - 12s 284us/sample - loss: 0.8642 - accuracy: 0.7264 - val_loss: 0.7129 - val_accuracy: 0.7769
Epoch 4/30
42000/42000 [==============================] - 12s 287us/sample - loss: 0.7911 - accuracy: 0.7510 - val_loss: 0.6367 - val_accuracy: 0.8043
Epoch 5/30
42000/42000 [==============================] - 13s 307us/sample - loss: 0.7393 - accuracy: 0.7667 - val_loss: 0.5911 - val_accuracy: 0.8213
Epoch 6/30
42000/42000 [==============================] - 13s 304us/sample - loss: 0.6967 - accuracy: 0.7808 - val_loss: 0.5595 - val_accuracy: 0.8279
Epoch 7/30
42000/42000 [====================

Implement backpropagation (cost stochastic gradient descent, cross entropy loss, cost functions

In [27]:
model1 = Sequential()
model1.add(Reshape((1024,),input_shape=(32,32,1,)))
model1.add(BatchNormalization())

model1.add(Dense(200, activation='relu', name='Layer_1'))
model1.add(Dense(100, activation='relu', name='Layer_2'))

model1.add(Dense(60, activation='relu', name='Layer_3'))
model1.add(Dense(30, activation='relu', name='Layer_4'))

model1.add(Dense(10, activation='softmax', name='Output'))

sgd =  optimizers.Adam(lr=0.002, beta_1=0.9, beta_2=0.999) # with decay values

model1.compile(optimizer=sgd, loss='categorical_crossentropy', metrics=['accuracy'])

model1.fit(X_train_c,y_train_c,          
          validation_data=(X_val_c,y_val_c),
          epochs=30,
          batch_size=32)

Train on 42000 samples, validate on 60000 samples
Epoch 1/30
42000/42000 [==============================] - 14s 324us/sample - loss: 1.4894 - accuracy: 0.4970 - val_loss: 1.0085 - val_accuracy: 0.6855
Epoch 2/30
42000/42000 [==============================] - 13s 301us/sample - loss: 1.0425 - accuracy: 0.6701 - val_loss: 0.8496 - val_accuracy: 0.7395
Epoch 3/30
42000/42000 [==============================] - 13s 304us/sample - loss: 0.9119 - accuracy: 0.7137 - val_loss: 0.7537 - val_accuracy: 0.7686
Epoch 4/30
42000/42000 [==============================] - 13s 318us/sample - loss: 0.8365 - accuracy: 0.7398 - val_loss: 0.7051 - val_accuracy: 0.7882
Epoch 5/30
42000/42000 [==============================] - 12s 297us/sample - loss: 0.7837 - accuracy: 0.7555 - val_loss: 0.6094 - val_accuracy: 0.8137
Epoch 6/30
42000/42000 [==============================] - 12s 298us/sample - loss: 0.7428 - accuracy: 0.7671 - val_loss: 0.6064 - val_accuracy: 0.8191
Epoch 7/30
42000/42000 [====================

We observe that with decay in this case, validation accuracy has reduced - in model1. We will continue to use the first model

In [0]:
y_pred = model.predict(X_test_c)

In [29]:
max_y_pred = np.zeros_like(y_pred)
max_y_pred[np.arange(len(y_pred)), y_pred.argmax(1)] = 1

max_y_pred

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32)

In [0]:
y_pred_classes = [np.argmax(y, axis=None, out=None) for y in max_y_pred]
y_test_classes = [np.argmax(y, axis=None, out=None) for y in y_test_c]

In [31]:

print(y_test_c)

[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]]


In [32]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test_classes, y_pred_classes)
print(cm)

[[1680   17    4   11   19    3   14   22   15   29]
 [ 106 1523   10   18   47   13    6   73   25    7]
 [  54   35 1515   40   17   12    7   62   20   41]
 [  50   41   23 1307   19  129   15   43   57   35]
 [  44   64   22    6 1577   13   19   16   10   41]
 [  24   20    8   63    9 1493   71   14   45   21]
 [  97   25   11   17   38   74 1478   17   63   12]
 [  41   59   21   17    7   12    6 1621   12   12]
 [  76   45   28   22   31   26   92   16 1422   54]
 [ 137   27   18   26   20   49   11   33   36 1447]]


In [33]:
from sklearn.metrics import classification_report
target_names = ['class 0', 'class 1', 'class 2', 'class 3', 'class 4', 'class 5', 'class 6', 'class 7', 'class 8', 'class 9']
print(classification_report(y_test_classes, y_pred_classes, target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.73      0.93      0.81      1814
     class 1       0.82      0.83      0.83      1828
     class 2       0.91      0.84      0.87      1803
     class 3       0.86      0.76      0.81      1719
     class 4       0.88      0.87      0.88      1812
     class 5       0.82      0.84      0.83      1768
     class 6       0.86      0.81      0.83      1832
     class 7       0.85      0.90      0.87      1808
     class 8       0.83      0.78      0.81      1812
     class 9       0.85      0.80      0.83      1804

    accuracy                           0.84     18000
   macro avg       0.84      0.84      0.84     18000
weighted avg       0.84      0.84      0.84     18000



Conclusion:

The classicial KNN trained model takes alot of time - approxiamtely 2 hrs and delivers lower accuracy scores. The image data is a bigger training set and distance calculations in KNN seem to take more time. In a Neural Network method, the prior layer and nodes feed into next layer which is must faster and optimized,and also the modeler has a control on Activation functions- type and number of neurons , learning rates , etc. Since the NN is much faster various trials with the network can be made to tune the model for higher accuracy.